import keyMirror from 'keymirror';

export const ACTIONS = keyMirror({
  RESET_PASSWORD_STATE: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILED: null,
  RESET_PASSWORD_ERROR: null,
  UPDATE_PASSWORD_SUCCESS: null,
  UPDATE_PASSWORD_FAILED: null,
  UPDATE_PASSWORD_ERROR: null,
  NEW_ARTICLE: null,
  NEW_ARTICLE_ERROR: null,
  UPDATE_ARTICLES_RESET_STATE: null,
  UPDATE_ARTICLES_SUCCESS: null,
  UPDATE_ARTICLES_ERROR: null,
  GET_ARTICLES_BY_ID_RESET_STATE: null,
  GET_ARTICLES_BY_ID_SUCCESS: null,
  GET_ARTICLES_BY_ID_ERROR: null,
});
