export const NEW_ACTION = '';
export const GLOBAL_START_LOADING = 'GLOBAL_START_LOADING';
export const GLOBAL_STOP_LOADING = 'GLOBAL_STOP_LOADING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
