import keyMirror from 'keymirror';

export const ACTIONS = keyMirror({
  RESET_PASSWORD_STATE: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILED: null,
  RESET_PASSWORD_ERROR: null,
  UPDATE_PASSWORD_SUCCESS: null,
  UPDATE_PASSWORD_FAILED: null,
  UPDATE_PASSWORD_ERROR: null,
  SET_CURRENT_USER: null,
  ARTICLES_RATING_SUCCESS: null,
  ARTICLES_RATING_ERROR: null,
  RESET_ARTICLES_RATING_STATE: null,
  GET_ARTICLES_RATING_SUCCESS: null,
  GET_ARTICLES_RATING_ERROR: null,
});
